#This container contains your model and any helper scripts specific to your model.
# When building the image inside mnist.ipynb the base docker image will be overwritten
FROM tensorflow/tensorflow:1.15.2-py3

RUN pip3 install numpy pandas sklearn boto3 cloudpickle

ENTRYPOINT ["/usr/local/bin/python"]
#CMD ["/opt/model.py"]
